### ISSUE TITLE
Is there a way to make llmcord not log messages received?

### ISSUE THREAD

**Issue by MrRubberDucky** [jakobdylanc/llmcord.py#55]
Heyo, great project! I'm curious if there's a way to get rid of Message received messages that include user's discord ID and their prompt. Even if it's just in-memory, I'd rather make my users feel that their private DM conversations are that, private.

I looked around at the documentation and didn't see anything like this there so uh, if it's not a feature yet then would it be possible to implement such a thing? :3

**Comment by jakobdylanc** [comment]
Good point, I'll think about this. Since llmcord.py does not impose any user rate limits I figured every message should get logged so you can monitor for abuse, etc...

For now you can easily disable it by commenting out this 1 line in llmcord.py (by adding a # at the beginning):
https://github.com/jakobdylanc/llmcord.py/blob/68d1ed0254a70042ff660016b8010d3d50f1d7f5/llmcord.py#L177

Or you can keep the logging but without the message content, by changing that line to:
```python
logging.info(f"Message received (user ID: {new_msg.author.id}, attachments: {len(new_msg.attachments)}, reply chain length: {len(reply_chain)})")
```

I'm curious to know more people's thoughts on this. Maybe I should just remove message content from the logging messages entirely? Maybe replace it with "character count" so you can still know the size of the message.

**Comment by jakobdylanc** [comment]
I'm curious to know more people's thoughts on this. Maybe I should just remove message content from the logging messages entirely? Maybe replace it with "character count" so you can still at least know the size of the message.

**Comment by tavdog** [comment]
could just pipe the output to /dev/null.

**Comment by jakobdylanc** [comment]
What do you mean exactly? I wouldn't want something that only works on Linux.

**Comment by tavdog** [comment]
I just meant you could pipe the output to /dev/null when running the script if you wanted to make sure the input wasn't being stored in memory.  But yes that would only work on linux.

**Comment by jakobdylanc** [comment]
Good point, that is the way. Closing :)
